require('conf.nvim-tree')
require('conf.nvim-treesitter')
require('conf.tokyonight')
require('conf.lualine')
require('conf.bufferline')
require('conf.comment')
require('conf.floaterm')
require('conf.symbols-outline')
